### ISSUE TITLE
Concluir pesquisa

### ISSUE THREAD

**Issue by ArthurCoelho25** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2022-2-e2-proj-int-t8-lista-de-tarefas-com-foco-em-tdah#1]
Coletar dados do questionário disponivel em. https://docs.google.com/forms/d/1uTDmM_Ifw6d5OnaKfeT09oFTYXcKntdniEYhjOyFLGk/edit?usp=sharing

**Comment by khaiocamargos** [comment]
TESTE ESTOU FAZENDO UM COMENTARIO DE TESTE

**Comment by khaiocamargos** [comment]
o arthur esta fazendo a pesquisa

**Comment by khaiocamargos** [comment]
olá arthurzaum
